media:
  - name: Images
    input: images
    output: /images
    path: images
    categories: [image]
  - name: Icons
    input: assets/icons
    output: /assets/icons
    path: icons
    categories: [image]
content:

  - name: pages
    label: Pages
    path: pages
    type: collection
    subfolders: false
    view:
      fields: [permalink, meta_title ]
      primary: meta_title
      sort: [meta_title]
    fields:
      - { name: body, label: Body, type: code, options: { language: markdown } }
      - { name: meta_description, type: string, label: Meta Description }
      - { name: meta_title, type: string, label: Meta Title }
      - name: eleventyNavigation
        label: Navigation
        type: object
        fields:
          - { name: key, type: string }
          - { name: parent, type: string }
          - { name: order, type: number }
      - { name: layout, type: string }
      - { name: permalink, type: string }

  - name: locations
    label: Locations
    path: locations
    type: collection
    subfolders: false
    view:
      fields: [permalink, meta_title ]
      primary: meta_title
      sort: [meta_title]
    fields:
      - { name: body, label: Body, type: code, options: { language: markdown } }
      - { name: meta_description, type: string, label: Meta Description }
      - { name: meta_title, type: string, label: Meta Title }
      - name: eleventyNavigation
        label: Navigation
        type: object
        fields:
          - { name: key, type: string }
          - { name: parent, type: string }
          - { name: order, type: number }
      - { name: permalink, type: string }
      
  - name: news
    label: News
    path: news
    type: collection
    subfolders: false
    fields:
      - { name: title, type: string, label: Title }
      - { name: date, label: Date, type: date }
      - { name: body, label: Body, type: code, options: { language: markdown } }
      - name: gallery
        type: image
        label: Gallery
        options: { multiple: { max: 1 } }
      - { name: meta_description, type: string, label: Meta Description }
      - { name: meta_title, type: string, label: Meta Title }
      
  - name: products
    label: Products
    path: products
    type: collection
    subfolders: false
    fields:
      - { name: title, type: string, label: Title }
      - name: categories
        label: Categories
        type: reference
        options:
          collection: categories
          multiple: true
          search: "title"
          value: "{path}"
          label: "{title}"
      - { name: price, label: Price, type: string }
      - { name: order, label: Display Order, type: number }
      - { name: body, label: Body, type: code, options: { language: markdown } }
      - { name: features, type: string, label: Features, list: true }
      - name: gallery
        type: image
        label: Gallery
        options: { multiple: true }
      - { name: meta_description, type: string, label: Meta Description }
      - { name: meta_title, type: string, label: Meta Title }
      
  - name: categories
    label: Categories
    path: categories
    type: collection
    subfolders: false
    filename: "{primary}.md"
    fields:
      - { name: title, type: string, label: Title }
      - { name: body, label: Body, type: code, options: { language: markdown } }
      - { name: meta_description, type: string, label: Meta Description }
      - { name: meta_title, type: string, label: Meta Title }
      - name: eleventyNavigation
        label: Navigation
        type: object
        fields:
          - { name: key, type: string }
          - { name: parent, type: string }
          - { name: order, type: number }
 
  - name: reviews
    label: Reviews
    path: reviews
    type: collection
    subfolders: false
    fields:
      - { name: name, type: string, label: Name }
      - { name: url, type: string, label: URL }
      - { name: rating, type: number, label: Rating, required: true }
      - { name: body, label: Body, type: code, options: { language: markdown } }
      - name: products
        label: Products
        type: reference
        options:
          collection: products
          multiple: true
          search: "title"
          value: "{path}"
          label: "{title}"

  - name: snippets
    label: Snippets
    path: snippets
    type: collection
    subfolders: false
    filename: '{primary}.md'
    fields:
      - { name: name, type: string, label: Name }
      - { name: body, label: Body, type: code, options: { language: markdown } }
  
  - name: home_content
    label: Homepage Content
    type: file
    path: _data/home_content.json
    format: json
    fields:
      - name: banner
        label: Banner Section
        type: object
        fields:
          - name: special_offer
            label: Special Offer
            type: object
            fields:
              - { name: message, type: string, label: Offer Message, required: true }
              - { name: link, type: string, label: Link URL, required: true }
          - name: images
            label: Banner Images
            type: image
            list: true
      - name: hero
        label: Hero Section
        type: object
        fields:
          - name: service_cards
            label: Service Cards
            type: object
            list: true
            fields:
              - { name: title, type: string, label: Title, required: true }
              - { name: description, type: text, label: Description, required: true }
              - { name: link, type: string, label: Link, required: true }
              - { name: image, type: image, label: Image }
      - name: main_content
        label: Main Content Section
        type: object
        fields:
          - name: paragraphs
            label: Content Paragraphs
            type: text
            list: true
          - { name: highlight, type: string, label: Highlight Text }
      - name: why_choose_us
        label: Why Choose Us Section
        type: object
        fields:
          - { name: heading, type: string, label: Section Heading, default: "Why Choose Us?" }
          - name: features
            label: Features
            type: object
            list: true
            fields:
              - { name: title, type: string, label: Feature Title, required: true }
              - { name: icon, type: image, label: Icon, media: Icons }
      - name: reviews
        label: Reviews Section
        type: object
        fields:
          - { name: heading, type: string, label: Section Heading, default: "Our Reviews" }
          - name: items
            label: Customer Reviews
            type: object
            list: true
            fields:
              - { name: text, type: text, label: Review Text, required: true }
              - { name: author, type: string, label: Author Name, required: true }
              - { name: date, type: string, label: Review Date }

  - name: site
    label: Site Configuration
    type: file
    path: _data/site.json
    fields:
      - { name: name, type: string, label: Site Name }
      - { name: url, type: string, label: Site URL }
      - name: opening_times
        label: Opening Times
        type: object
        list: true
        fields:
          - { name: day, type: string, label: Day, required: true }
          - { name: hours, type: string, label: Hours, required: true }
      - name: socials
        label: Social Media Links
        type: object
        fields:
          - { name: Github, type: string, label: Github }
          - { name: Forgejo, type: string, label: Forgejo }
          - { name: Facebook, type: string, label: Facebook }
          - { name: Instagram, type: string, label: Instagram }
          - { name: TikTok, type: string, label: TikTok }
          - { name: Google, type: string, label: Google }
          - { name: WhatsApp, type: string, label: WhatsApp }
          - { name: RSS, type: string, label: RSS }
      - { name: map_embed_src, type: string, label: Map Embed URL }
      
  - name: meta
    label: Meta Configuration
    type: file
    path: _data/meta.json
    fields:
      - { name: language, type: string, label: Language Code, default: "en-GB" }
      - name: organization
        label: Organization
        type: object
        fields:
          - { name: description, type: string, label: Organization Description }
          - { name: legalName, type: string, label: Legal Name }
          - { name: foundingDate, type: string, label: Founding Date }
          - name: founders
            label: Founders
            type: object
            list: true
            fields:
              - { name: name, type: string, label: Name }
          - name: address
            label: Address
            type: object
            fields:
              - { name: streetAddress, type: string, label: Street Address }
              - { name: addressLocality, type: string, label: City }
              - { name: addressRegion, type: string, label: Region/State }
              - { name: postalCode, type: string, label: Postal Code }
              - { name: addressCountry, type: string, label: Country Code }
          - name: contactPoint
            label: Contact Points
            type: object
            list: true
            fields:
              - { name: telephone, type: string, label: Telephone }
              - { name: contactType, type: string, label: Contact Type }
              - { name: areaServed, type: string, label: Area Served }
              - { name: availableLanguage, type: string, label: Available Languages, list: true }
